version: '2.1'

services:
  hello-node:
    image: hello-node
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8081:8081
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js